[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
lending = "EZZtc7TU4Dd5Bc1wdQZ9szhsv3cavuHzNCy8Laq1beLU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
